### ISSUE TITLE
support seconds in date_breaks

### ISSUE THREAD

**Issue by datagiraffe** [has2k1/mizani#12]
`date_breaks` does not support seconds:
https://mizani.readthedocs.io/en/stable/breaks.html#mizani.breaks.date_breaks
says 

> **width** ... Must be one of [minute, hour, day, week, month, year]

I guess this could be solved by including `SecondLocator` from `matplotlib.dates`
Maybe it would also make sense to add the `MicrosecondLocator`

**Comment by has2k1** [comment]
@datagiraffe, you are right. I do not know why I did not include them in the first place.
