### ISSUE TITLE
Missing dependencies: dateutil and docs/test dependencies

### ISSUE THREAD

**Issue by juliangilbey** [has2k1/mizani#19]
Hi!
Another missing dependency issue (like https://github.com/has2k1/plydata/issues/25).  In addition to the docs/test dependencies not listed in `setup.py`, I see that `dateutil` is imported by `mizani/transforms.py`, but is not listed in `setup.py`.  In the test suite, the package `pytz` is also used.
I'm looking forward to using `plotnine` :-)
Best wishes!

**Comment by juliangilbey** [comment]
Oh, and another one: `scipy` is imported in `mizani/transforms.py`, so needs to be added as well.

**Comment by has2k1** [comment]
dateutil is brought in by Matplotlib (I think), but I guess it is proper to
be explicit about it as a requirement.

For scipy, it should be in the extra_requires at the minimum.

**Comment by has2k1** [comment]
I see you have filled a bunch of issues but for now my involvement is
limited. My ISP has blocked me from accessing github.

**Comment by juliangilbey** [comment]
You're right about `dateutil`!  Sorry about your ISP - that's crazy.  I hope you get it sorted!

**Comment by juliangilbey** [comment]
I'm less sure about `scipy` though - it's used by `logit_trans` and `probit_trans`, and the import in `probability_trans` is not protected in a `try`/`except` block.
