### ISSUE TITLE
Spotted incompatibility problem

### ISSUE THREAD

**Issue by morales-cmd** [has2k1/mizani#33]
Latest release 0.10.0 is incompatible with some other dependencies (I spotted it while working on plantcv package). To fix it I needed to downgrade to 0.9.2. Not sure if you are interested in fixing that, just wanted to mention it.

**Comment by has2k1** [comment]
I think plotnine is the only package that directly depends on mizani. The latest version of plotnine (released before) requires mizani<0.10.0.

I thought I had made it unlikely

**Comment by ethan-wicker** [comment]
To add detail here, version 0.10.0 of mizani is incompatible with Databricks runtimes as well, so the import of plotnine fails.  Specifically, I tested this on Databricks Runtime versions [12.1 ML](https://docs.databricks.com/en/release-notes/runtime/12.1ml.html) and [11.3](https://docs.databricks.com/en/release-notes/runtime/11.3lts.html).

The specific error returned is 
`ImportError: cannot import name 'multitype_sort' from 'mizani.utils' (/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/mizani/utils.py)`

Forcing a downgraded install of mizani==0.9.2 does resolve the issue.  Thanks @morales-cmd for this suggestion.

And thanks @has2k1 for the awesome plotnine package!
