### ISSUE TITLE
Date labels missing

### ISSUE THREAD

**Issue by nprihodko** [has2k1/mizani#42]
After updating plotnine from 0.12.4 to 0.13.5 (this also triggers mizani update from 0.9.3 to 0.11.2) date labels stopped working.

Seems like it breaks when there are more than 3 observations (but maybe there are also other conditions).

All good:
```python
import pandas as pd
from plotnine import *


plot_df = pd.DataFrame(
    {
        "x": ["2023-01-01", "2023-02-01", "2023-03-01"],
        "y": [1, 2, 3],
    }
)
plot_df["x"] = pd.to_datetime(plot_df["x"])
ggplot(plot_df, aes(x="x", y="y")) + geom_point()
```

<img src="https://github.com/has2k1/plotnine/assets/67439573/2ea89de1-1420-497a-8fc7-c7fcd384eec3" width=65% height=65%>

But if I add one more row, date axis breaks:
```python
plot_df = pd.DataFrame(
    {
        "x": ["2023-01-01", "2023-02-01", "2023-03-01", "2023-04-01"],
        "y": [1, 2, 3, 4],
    }
)
plot_df["x"] = pd.to_datetime(plot_df["x"])
ggplot(plot_df, aes(x="x", y="y")) + geom_point()
```

<img src="https://github.com/has2k1/plotnine/assets/67439573/81daf63f-8718-466e-86a2-7d8ac045c83e" width=65% height=65%>

Adding `scale_x_datetime()` or `scale_x_date()` explicitly does not affect anything.

**Comment by has2k1** [comment]
Fix have been released in mizani `v0.11.3`.
