### ISSUE TITLE
Comparison between tz-naive and tz-aware datetime objects due to `floor_hour` timezone erasure

### ISSUE THREAD

**Issue by broad-well** [has2k1/mizani#45]
I haven't had time to find the exact conditions that trigger the condition described in the title, but from a little digging in my debugger, I found the following behavior in [`date_utils.py`](https://github.com/has2k1/mizani/blob/main/mizani/_core/date_utils.py):

```python
>>> floor_hour(datetime.datetime(2022, 12, 22, 8, 10, tzinfo=datetime.timezone.utc))
datetime.datetime(2022, 12, 22, 8, 0)
```
This effectively erases the timezone information. In my case, the return value is then compared to a timezone-aware datetime value from my dataset, which produces an error.

**Comment by broad-well** [comment]
```python
def floor_day(d: datetime) -> datetime:
    """
    Round down to the start of the day
    """
    return d.min.replace(d.year, d.month, d.day, tzinfo=d.tzinfo) if has_time(d) else d
```
This appears to fix it on my end.

**Comment by has2k1** [comment]
Thanks for solution. It indeed was an oversight.
