### ISSUE TITLE
date_format doesn't respect localized time zone

### ISSUE THREAD

**Issue by lorin** [has2k1/mizani#8]
date_format doesn't respect the time zone of a `pandas.Timestamp`:

```
>>> from mizani.formatters import date_format
>>> import pandas as pd
>>>
>>> ts_utc = pd.Timestamp('2017-11-30 23:16:00', tz='UTC')
>>> ts_pst = ts_utc.tz_convert('US/Pacific')
>>> ts_pst.strftime("%H")
'15'
>>> date_format("%H")([tc_pst])
['23']
```

**Comment by has2k1** [comment]
Work around

```
>>> f = date_format("%H")
>>> f.formatter.tz = ts_pst.tz
>>> f([ts_pst])
['15']
```

**Comment by has2k1** [comment]
The issue is, because we use Matplotlib internals the most sane solution would be to use the timezone of the first date. So if you pass the format functions times with different dates the result may be surprising.

**Comment by lorin** [comment]
Seems reasonable, and it would cover my use case.

If you were concerned about a user submitting different timezones, you could do a check that they are all the same and emit a warning if they aren't.
